export const PLAYLIST = [
  { id:"s1",  title:"All Your Exes",                         artist:"Julia Michaels",                              health:0, youtubeId:"REKWd0u7YgU", spotifyUri:"spotify:track:4kMgpLBKVRmQE0MRRQDKNA", duration:189 },
  { id:"s2",  title:"Find Me",                               artist:"Nate Mitchell",                               health:0, youtubeId:"Adgm-MlnB3Y", duration:210 },
  { id:"s3",  title:"ANGELS LIKE ME",                        artist:"Ryan Oakes, SkyDxddy",                        health:0, youtubeId:"kTrPxxOp4Gw", duration:195 },
  { id:"s4",  title:"Apathy Anthem",                         artist:"MaeThePirate",                                health:0, youtubeId:"5jARpPOVrCY", duration:200 },
  { id:"s5",  title:"Alien (Sped Up)",                       artist:"Nico & Chelsea",                              health:0, youtubeId:"1iL3mZLazt0", duration:165 },
  { id:"s6",  title:"I HOPE YOUR CAR BREAKS DOWN",           artist:"MaeThePirate",                                health:0, youtubeId:"a5p5ZSTHinw", duration:180 },
  { id:"s7",  title:"Talking To A Ghost",                    artist:"YOUTHYEAR",                                   health:0, youtubeId:"kZHKdeqTuug", duration:210 },
  { id:"s8",  title:"Best Part Of The Story",                artist:"SkyDxddy",                                    health:0, youtubeId:"4Av1L5Rmoj0", duration:200 },
  { id:"s9",  title:"God Of War",                            artist:"SkyDxddy",                                    health:0, youtubeId:"isvwPvc6Dqk", duration:195 },
  { id:"s10", title:"SNAP",                                  artist:"Rosa Linn",                                   health:0, youtubeId:"Lo4_K4relMg", spotifyUri:"spotify:track:4CsGPRKLjR2VHXFE6gHIQp", duration:178 },
  { id:"s11", title:"kill the girl",                         artist:"L\u00d8L\u00d8",                                        health:0, youtubeId:"zmH7PJiR2yk", duration:190 },
  { id:"s12", title:"5,6,7,8",                               artist:"L\u00d8L\u00d8, girlfriends",                           health:0, youtubeId:"NVOhlLfcQ7U", duration:185 },
  { id:"s13", title:"It Wasn't Easy To Be Happy For You",    artist:"The Lumineers",                               health:0, youtubeId:"eGReASgVM1Q", spotifyUri:"spotify:track:3l2NQJS9LK87ChVVMVSxD7", duration:222 },
  { id:"s14", title:"What's Stopping You",                   artist:"P!X!E",                                       health:0, youtubeId:"o1wxgIps1e4", duration:195 },
  { id:"s15", title:"WATCH THIS",                            artist:"TAELA",                                       health:0, youtubeId:"iycrMFBrnsg", duration:180 },
  { id:"s16", title:"If I Died Last Night",                  artist:"Jessie Murph",                                health:0, youtubeId:"pRtO5vlJnWw", spotifyUri:"spotify:track:7G5M0duiNDVuHDKmFqjlqf", duration:200 },
  { id:"s17", title:"People That I Love Leave",              artist:"Cassadee Pope",                               health:0, youtubeId:"eEF8T2F92AE", duration:210 },
  { id:"s18", title:"Starduhst",                             artist:"honestav",                                    health:0, youtubeId:"3O-2kCcI-hg", duration:185 },
  { id:"s19", title:"Bullet",                                artist:"Hollywood Undead",                            health:0, youtubeId:"lP077RitNAc", spotifyUri:"spotify:track:0tJ9xhZIAICAjJuNal9hAK", duration:216 },
  { id:"s20", title:"Such Small Hands",                      artist:"La Dispute",                                  health:0, youtubeId:"XlppZKMYNys", spotifyUri:"spotify:track:1K3lbDfFMPB6pQDQbMHJPe", duration:135 },
  { id:"s21", title:"Sara",                                  artist:"We Three",                                    health:0, youtubeId:"IlvELjeisqE", duration:245 },
  { id:"s22", title:"HELLO L\u00d8NELINESS",                      artist:"Ekoh, L\u00f8 Spirit",                             health:0, youtubeId:"wAtFJAqTVhA", duration:200 },
  { id:"s23", title:"Lilith",                                artist:"Halsey",                                      health:0, youtubeId:"9PdH-zavwO4", spotifyUri:"spotify:track:4OF29bVGvMgEKsBqvYCGhb", duration:195 },
  { id:"s24", title:"007",                                   artist:"L\u00d8L\u00d8",                                        health:0, youtubeId:"4okJouEbZ_s", duration:180 },
  { id:"s25", title:"GrokBlocked",                           artist:"Pie For Billy",                               health:0, youtubeId:"gGcKxx0yvfE", duration:210 },
  { id:"s26", title:"Mud",                                   artist:"CARR",                                        health:0, youtubeId:"g9X2aSt15jQ", duration:200 },
  { id:"s27", title:"Enemy",                                 artist:"Arrested Youth",                              health:0, youtubeId:"z3PXjKxEkjo", duration:190 },
  { id:"s28", title:"Panic Room",                            artist:"Au/Ra",                                       health:0, youtubeId:"Ro51SuLyh8A", spotifyUri:"spotify:track:3SBqFkXIaKv10AAj8bJUGP", duration:189 },
  { id:"s29", title:"Dominoes",                              artist:"Ren",                                         health:0, youtubeId:"bbbjWEnC3Gc", duration:240 },
  { id:"s30", title:"Full Circle",                           artist:"Movements",                                   health:0, youtubeId:"nVKzdqvfjO8", duration:210 },
  { id:"s31", title:"All Around Me",                         artist:"Flyleaf",                                     health:0, youtubeId:"xN0FFK8JSYE", spotifyUri:"spotify:track:5KR1fUFJJPMQ60XPoLr2tN", duration:215 },
  { id:"s32", title:"Medusa",                                artist:"Cameron Whitcomb",                            health:0, youtubeId:"KNE8o4gK_y0", duration:200 },
  { id:"s33", title:"Dopamine",                              artist:"Sum 41",                                      health:0, youtubeId:"yYk2BTwuQnM", duration:195 },
  { id:"s34", title:"Anxiety",                               artist:"Bmike",                                       health:0, youtubeId:"KhnEUbbMWUM", duration:210 },
  { id:"s35", title:"Teenage Dirtbag",                       artist:"Postmodern Jukebox, Jax",                     health:0, youtubeId:"Snh-ufvXWIk", duration:230 },
  { id:"s36", title:"I Dare You",                            artist:"Shinedown",                                   health:0, youtubeId:"R5kaDyq41qw", spotifyUri:"spotify:track:3lSOmfRVVP6fRImEaZkJBi", duration:215 },
  { id:"s37", title:"Baby Don't Cut (Acoustic)",             artist:"Bmike",                                       health:0, youtubeId:"0Dr0ibhVs0I", duration:240 },
  { id:"s38", title:"Freckles",                              artist:"honestav",                                    health:0, youtubeId:"BM8y6sVVH2E", duration:185 },
  { id:"s39", title:"The Other Side",                        artist:"Michael Marcagi",                             health:0, youtubeId:"TuQ4im63cMY", duration:195 },
  { id:"s40", title:"HORROR SHOW",                           artist:"Hot Milk",                                    health:0, youtubeId:"OBZ84gQlBtc", duration:200 },
  { id:"s41", title:"BLOSSOM",                               artist:"R\u00d8RY",                                        health:0, youtubeId:"Ya8dZyiD2gE", duration:190 },
  { id:"s42", title:"For the Misfits",                       artist:"SkyDxddy",                                    health:0, youtubeId:"WurYAHXEMXQ", duration:200 },
  { id:"s43", title:"Dear Diary",                            artist:"KidShazam, SkyDxddy, PONS",                   health:0, youtubeId:"IGgxRH7B86M", duration:210 },
  { id:"s44", title:"Angel of Death",                        artist:"SkyDxddy",                                    health:0, youtubeId:"-_GBaVjCsOc", duration:195 },
  { id:"s45", title:"i like the way you kiss me",            artist:"Artemas",                                     health:0, youtubeId:"evJ6gX1lp2o", spotifyUri:"spotify:track:5W1XY5ucNATjTVLMDpGGig", duration:138 },
  { id:"s46", title:"You Are Enough",                        artist:"Citizen Soldier",                             health:0, youtubeId:"rZLVIVByZn8", duration:225 },
  { id:"s47", title:"Psycho",                                artist:"Taylor Acorn",                                health:0, youtubeId:"iOVGmrypaAE", duration:190 },
  { id:"s48", title:"cinderella's dead",                     artist:"EMELINE",                                     health:0, youtubeId:"Tf7qp1CwanI", spotifyUri:"spotify:track:6IQBJpLSJBHGKKkSladarQ", duration:180 },
  { id:"s49", title:"For a Pessimist, I'm Pretty Optimistic",artist:"Paramore",                                   health:0, youtubeId:"B1o2UCLvD38", spotifyUri:"spotify:track:3qhlB30KknSejmIvZFLlEi", duration:229 },
  { id:"s50", title:"Weightless",                            artist:"All Time Low",                                health:0, youtubeId:"TpG3BxRctQ4", spotifyUri:"spotify:track:2uFaJJtFpPDc5Pa95XzTvg", duration:195 },
];
